# For local phase configurations
application:
  name: financial-statistics-service
server:
  port: 54000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shop.voyagerss.com:3306/charger?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true&createDatabaseIfNotExist=true
    username: charger
    password: wjsrlck1@
    jpa:
      show-sql: false
      generate-ddl: true
      hibernate:
        ddl-auto: none
        naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
    #        database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      host: mongodb://fn:dugodwk1@shop.voyagerss.com/fn?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000
      database: fn
      authentication-database: admin
      username: fn
      password: dugodwk1



springdoc:
  version: '1.0.0'
  api-docs:
    groups:
      enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match: /**

#OAuth2
encodeKey: secret
#Email account info
email.account: en9door
email.password: dbstnr7079&
#REST API
kakao.client.id: e32a4d819f76b2ca4e652a2477ecf982
#kakao pay
kakao.admin.key: 9182554bcd6244da75828cfed4e62a65

#app:
ecos-api-key: A3KS6JOGXDYWDBC2XQ3Y
file:
  upload-dir: C:\ftp



---
spring:
  config:
    activate:
      on-profile: local


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hibernate:
      ddl-auto: update

